--- Installing dependencies ---
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
--- Running main.py ---
[I 2024-12-06 23:45:34,601] A new study created in memory with name: no-name-d95d1e6a-de70-40e0-8011-a2449645772f
[I 2024-12-07 00:11:40,533] Trial 0 finished with value: -1.128333330154419 and parameters: {'lr': 0.001, 'gamma': 0.8, 'max_grad_norm': 0.5, 'tau': 0.1, 'memory_size': 400}. Best is trial 0 with value: -1.128333330154419.
[I 2024-12-07 00:37:41,254] Trial 1 finished with value: -1.0440000295639038 and parameters: {'lr': 0.001, 'gamma': 0.8, 'max_grad_norm': 2.0, 'tau': 0.1, 'memory_size': 400}. Best is trial 1 with value: -1.0440000295639038.
[I 2024-12-07 01:02:54,306] Trial 2 finished with value: -1.1053333282470703 and parameters: {'lr': 0.0001, 'gamma': 0.85, 'max_grad_norm': 0.5, 'tau': 0.1, 'memory_size': 400}. Best is trial 1 with value: -1.0440000295639038.
[I 2024-12-07 01:28:18,877] Trial 3 finished with value: -1.1130000352859497 and parameters: {'lr': 0.0001, 'gamma': 0.95, 'max_grad_norm': 1.5, 'tau': 0.01, 'memory_size': 300}. Best is trial 1 with value: -1.0440000295639038.
[I 2024-12-07 01:53:51,120] Trial 4 finished with value: -1.1206666231155396 and parameters: {'lr': 0.001, 'gamma': 0.95, 'max_grad_norm': 1.0, 'tau': 0.001, 'memory_size': 300}. Best is trial 1 with value: -1.0440000295639038.
[I 2024-12-07 02:19:11,617] Trial 5 finished with value: -1.0823333263397217 and parameters: {'lr': 1e-05, 'gamma': 0.95, 'max_grad_norm': 1.5, 'tau': 0.001, 'memory_size': 200}. Best is trial 1 with value: -1.0440000295639038.
[I 2024-12-07 02:44:24,190] Trial 6 finished with value: -0.9980000257492065 and parameters: {'lr': 0.0001, 'gamma': 0.85, 'max_grad_norm': 0.5, 'tau': 0.1, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 03:09:41,971] Trial 7 finished with value: -1.1360000371932983 and parameters: {'lr': 0.001, 'gamma': 0.95, 'max_grad_norm': 0.5, 'tau': 0.001, 'memory_size': 300}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 03:34:58,524] Trial 8 finished with value: -1.0210000276565552 and parameters: {'lr': 1e-05, 'gamma': 0.95, 'max_grad_norm': 1.0, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 04:00:00,564] Trial 9 finished with value: -1.097666621208191 and parameters: {'lr': 1e-05, 'gamma': 0.95, 'max_grad_norm': 1.0, 'tau': 0.1, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 04:25:14,219] Trial 10 finished with value: -1.1283332109451294 and parameters: {'lr': 0.01, 'gamma': 0.85, 'max_grad_norm': 2.0, 'tau': 0.1, 'memory_size': 200}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 04:50:28,317] Trial 11 finished with value: -1.097666621208191 and parameters: {'lr': 0.0001, 'gamma': 0.9, 'max_grad_norm': 1.0, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 05:15:44,529] Trial 12 finished with value: -1.097666621208191 and parameters: {'lr': 1e-05, 'gamma': 0.99, 'max_grad_norm': 0.5, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 05:41:07,126] Trial 13 finished with value: -1.0516667366027832 and parameters: {'lr': 0.01, 'gamma': 0.85, 'max_grad_norm': 1.0, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 06:06:31,478] Trial 14 finished with value: -1.090000033378601 and parameters: {'lr': 1e-05, 'gamma': 0.9, 'max_grad_norm': 0.5, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 06:32:04,390] Trial 15 finished with value: -1.0670000314712524 and parameters: {'lr': 0.0001, 'gamma': 0.99, 'max_grad_norm': 1.0, 'tau': 0.1, 'memory_size': 200}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 06:57:25,987] Trial 16 finished with value: -1.0210000276565552 and parameters: {'lr': 1e-05, 'gamma': 0.85, 'max_grad_norm': 1.5, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 07:22:47,668] Trial 17 finished with value: -1.1513333320617676 and parameters: {'lr': 0.0001, 'gamma': 0.85, 'max_grad_norm': 2.0, 'tau': 0.01, 'memory_size': 400}. Best is trial 6 with value: -0.9980000257492065.
[I 2024-12-07 07:48:00,791] Trial 18 finished with value: -1.1436666250228882 and parameters: {'lr': 0.01, 'gamma': 0.9, 'max_grad_norm': 1.0, 'tau': 0.1, 'memory_size': 300}. Best is trial 6 with value: -0.9980000257492065.
Exception in thread Thread-199837 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199838 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199839 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199840 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199841 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199842 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199843 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199844 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199845 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199846 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199847 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199848 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199849 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199850 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199851 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199852 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199853 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199854 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199855 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199856 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199857 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199858 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199859 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199860 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199861 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199862 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199863 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199864 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199865 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199866 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199867 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199868 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199869 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199870 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199871 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199872 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199873 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199874 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199875 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199876 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199877 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199878 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199879 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199880 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199881 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199882 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199883 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199884 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199885 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199886 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199887 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199888 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199889 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199890 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199891 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199892 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199893 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199894 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199895 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199896 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199897 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199898 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199899 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199900 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199901 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199902 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199903 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199904 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199905 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199906 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199907 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199908 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199909 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199910 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199911 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199912 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199913 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199914 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199915 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199916 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199917 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199918 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199919 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199920 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199921 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199922 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199923 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199924 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199925 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199926 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199927 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199928 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199929 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199930 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199931 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199932 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199933 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199934 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199935 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199936 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199937 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199938 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199939 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199940 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199941 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199942 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199943 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199944 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199945 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199946 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199947 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199948 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199949 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199950 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199951 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199952 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199953 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199954 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199955 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199956 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199957 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199958 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199959 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199960 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199961 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199962 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199963 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199964 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199965 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199966 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199967 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199968 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199969 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199970 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199971 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199972 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199973 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199974 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199975 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199976 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199977 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199978 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199979 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199980 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199981 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199982 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199983 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199984 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199985 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199986 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199987 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199988 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199989 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199990 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199991 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199992 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199993 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199994 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199995 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199996 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199997 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199998 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-199999 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
Exception in thread Thread-200000 (_record):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/RouteRL/environment/environment.py", line 454, in _record
    self.recorder.record(dc_episode, dc_ep_observations, rewards, cost_tables)#, self.det_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/services/recorder.py", line 52, in record
    self.remember_episode(episode, ep_observations, rewards, cost_tables)
  File "/app/RouteRL/services/recorder.py", line 68, in remember_episode
    merged_df.write_csv(make_dir(self.episodes_folder, f"ep{episode}.csv"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 79, in make_dir
    os.mkdir(path)
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/training_records/episodes/episodes'
[I 2024-12-07 08:13:11,775] Trial 19 finished with value: -1.159000039100647 and parameters: {'lr': 0.0001, 'gamma': 0.8, 'max_grad_norm': 0.5, 'tau': 0.001, 'memory_size': 200}. Best is trial 6 with value: -0.9980000257492065.
[W 2024-12-07 08:13:11,780] Trial 20 failed with parameters: {'lr': 1e-05, 'gamma': 0.99, 'max_grad_norm': 1.0, 'tau': 0.1, 'memory_size': 400} because of the following error: OSError(116, 'Stale file handle').
Traceback (most recent call last):
  File "/home/psarou/.local/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/app/experiments/trials_on_two_routes/mutation_sac_optuna.py", line 64, in objective
  File "/app/RouteRL/utilities/utils.py", line 20, in get_params
    params = read_json(file_path)
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 54, in read_json
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/params.json'
[W 2024-12-07 08:13:11,784] Trial 20 failed with value None.



SAC OPTUNA






SAC optuna



[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
[CONFIRMED] Environment variable exists: SUMO_HOME
[SUCCESS] Added module directory: /usr/share/sumo/tools
 Retrying in 1 seconds
Traceback (most recent call last):
  File "/app/experiments/trials_on_two_routes/mutation_sac_optuna.py", line 256, in <module>
  File "/home/psarou/.local/lib/python3.12/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/home/psarou/.local/lib/python3.12/site-packages/optuna/study/_optimize.py", line 63, in _optimize
    _optimize_sequential(
  File "/home/psarou/.local/lib/python3.12/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psarou/.local/lib/python3.12/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/home/psarou/.local/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/app/experiments/trials_on_two_routes/mutation_sac_optuna.py", line 64, in objective
  File "/app/RouteRL/utilities/utils.py", line 20, in get_params
    params = read_json(file_path)
             ^^^^^^^^^^^^^^^^^^^^
  File "/app/RouteRL/utilities/utils.py", line 54, in read_json
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 116] Stale file handle: 'experiments/trials_on_two_routes/params.json'
Exception ignored in atexit callback: <function dump_compile_times at 0x7faf84271760>
Traceback (most recent call last):
  File "/home/psarou/.local/lib/python3.12/site-packages/torch/_dynamo/utils.py", line 335, in dump_compile_times
    log.info(compile_times(repr="str", aggregate=True))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psarou/.local/lib/python3.12/site-packages/torch/_dynamo/utils.py", line 322, in compile_times
    out += tabulate(rows, headers=("Function", "Runtimes (s)"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/psarou/.local/lib/python3.12/site-packages/torch/_dynamo/utils.py", line 127, in tabulate
    import tabulate
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1525, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1499, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1602, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1645, in _fill_cache
OSError: [Errno 116] Stale file handle: '/app/experiments/trials_on_two_routes'
